// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travellers.Context;

#nullable disable

namespace Travellers.Migrations
{
    [DbContext(typeof(TravellerContext))]
    partial class TravellerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Travellers.Models.Traveller", b =>
                {
                    b.Property<int>("Traveller_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Traveller_Id"));

                    b.Property<long?>("Traveller_Contact")
                        .HasColumnType("bigint");

                    b.Property<string>("Traveller_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traveller_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traveller_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Traveller_Id");

                    b.ToTable("Travellers");
                });
#pragma warning restore 612, 618
        }
    }
}
